// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ddl.proto

package plugin

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OnDelete int32

const (
	OnDelete_NONE      OnDelete = 0
	OnDelete_CASCADE   OnDelete = 1
	OnDelete_NO_ACTION OnDelete = 2
)

var OnDelete_name = map[int32]string{
	0: "NONE",
	1: "CASCADE",
	2: "NO_ACTION",
}

var OnDelete_value = map[string]int32{
	"NONE":      0,
	"CASCADE":   1,
	"NO_ACTION": 2,
}

func (x OnDelete) String() string {
	return proto.EnumName(OnDelete_name, int32(x))
}

func (OnDelete) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ddb477f58283b30a, []int{0}
}

type Schema struct {
	Database             string      `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Table                string      `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	PrimaryKey           string      `protobuf:"bytes,3,opt,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	Interleave           *Interleave `protobuf:"bytes,4,opt,name=interleave,proto3" json:"interleave,omitempty"`
	Index                []*Index    `protobuf:"bytes,5,rep,name=index,proto3" json:"index,omitempty"`
	Import               []*Import   `protobuf:"bytes,6,rep,name=import,proto3" json:"import,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Schema) Reset()         { *m = Schema{} }
func (m *Schema) String() string { return proto.CompactTextString(m) }
func (*Schema) ProtoMessage()    {}
func (*Schema) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddb477f58283b30a, []int{0}
}

func (m *Schema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schema.Unmarshal(m, b)
}
func (m *Schema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schema.Marshal(b, m, deterministic)
}
func (m *Schema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schema.Merge(m, src)
}
func (m *Schema) XXX_Size() int {
	return xxx_messageInfo_Schema.Size(m)
}
func (m *Schema) XXX_DiscardUnknown() {
	xxx_messageInfo_Schema.DiscardUnknown(m)
}

var xxx_messageInfo_Schema proto.InternalMessageInfo

func (m *Schema) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *Schema) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *Schema) GetPrimaryKey() string {
	if m != nil {
		return m.PrimaryKey
	}
	return ""
}

func (m *Schema) GetInterleave() *Interleave {
	if m != nil {
		return m.Interleave
	}
	return nil
}

func (m *Schema) GetIndex() []*Index {
	if m != nil {
		return m.Index
	}
	return nil
}

func (m *Schema) GetImport() []*Import {
	if m != nil {
		return m.Import
	}
	return nil
}

type Interleave struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	OnDelete             OnDelete `protobuf:"varint,2,opt,name=on_delete,json=onDelete,proto3,enum=spanner.ddl.OnDelete" json:"on_delete,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Interleave) Reset()         { *m = Interleave{} }
func (m *Interleave) String() string { return proto.CompactTextString(m) }
func (*Interleave) ProtoMessage()    {}
func (*Interleave) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddb477f58283b30a, []int{1}
}

func (m *Interleave) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interleave.Unmarshal(m, b)
}
func (m *Interleave) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interleave.Marshal(b, m, deterministic)
}
func (m *Interleave) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interleave.Merge(m, src)
}
func (m *Interleave) XXX_Size() int {
	return xxx_messageInfo_Interleave.Size(m)
}
func (m *Interleave) XXX_DiscardUnknown() {
	xxx_messageInfo_Interleave.DiscardUnknown(m)
}

var xxx_messageInfo_Interleave proto.InternalMessageInfo

func (m *Interleave) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Interleave) GetOnDelete() OnDelete {
	if m != nil {
		return m.OnDelete
	}
	return OnDelete_NONE
}

type Index struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Columns              string   `protobuf:"bytes,2,opt,name=columns,proto3" json:"columns,omitempty"`
	NullFiltered         bool     `protobuf:"varint,3,opt,name=null_filtered,json=nullFiltered,proto3" json:"null_filtered,omitempty"`
	Unique               bool     `protobuf:"varint,4,opt,name=unique,proto3" json:"unique,omitempty"`
	Storing              string   `protobuf:"bytes,5,opt,name=storing,proto3" json:"storing,omitempty"`
	Interleave           string   `protobuf:"bytes,6,opt,name=interleave,proto3" json:"interleave,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Index) Reset()         { *m = Index{} }
func (m *Index) String() string { return proto.CompactTextString(m) }
func (*Index) ProtoMessage()    {}
func (*Index) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddb477f58283b30a, []int{2}
}

func (m *Index) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Index.Unmarshal(m, b)
}
func (m *Index) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Index.Marshal(b, m, deterministic)
}
func (m *Index) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Index.Merge(m, src)
}
func (m *Index) XXX_Size() int {
	return xxx_messageInfo_Index.Size(m)
}
func (m *Index) XXX_DiscardUnknown() {
	xxx_messageInfo_Index.DiscardUnknown(m)
}

var xxx_messageInfo_Index proto.InternalMessageInfo

func (m *Index) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Index) GetColumns() string {
	if m != nil {
		return m.Columns
	}
	return ""
}

func (m *Index) GetNullFiltered() bool {
	if m != nil {
		return m.NullFiltered
	}
	return false
}

func (m *Index) GetUnique() bool {
	if m != nil {
		return m.Unique
	}
	return false
}

func (m *Index) GetStoring() string {
	if m != nil {
		return m.Storing
	}
	return ""
}

func (m *Index) GetInterleave() string {
	if m != nil {
		return m.Interleave
	}
	return ""
}

type Import struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Import) Reset()         { *m = Import{} }
func (m *Import) String() string { return proto.CompactTextString(m) }
func (*Import) ProtoMessage()    {}
func (*Import) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddb477f58283b30a, []int{3}
}

func (m *Import) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Import.Unmarshal(m, b)
}
func (m *Import) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Import.Marshal(b, m, deterministic)
}
func (m *Import) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Import.Merge(m, src)
}
func (m *Import) XXX_Size() int {
	return xxx_messageInfo_Import.Size(m)
}
func (m *Import) XXX_DiscardUnknown() {
	xxx_messageInfo_Import.DiscardUnknown(m)
}

var xxx_messageInfo_Import proto.InternalMessageInfo

func (m *Import) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Import) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Column struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Length               int32    `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	Nullable             bool     `protobuf:"varint,3,opt,name=nullable,proto3" json:"nullable,omitempty"`
	AllowCommitTimestamp bool     `protobuf:"varint,4,opt,name=allow_commit_timestamp,json=allowCommitTimestamp,proto3" json:"allow_commit_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Column) Reset()         { *m = Column{} }
func (m *Column) String() string { return proto.CompactTextString(m) }
func (*Column) ProtoMessage()    {}
func (*Column) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddb477f58283b30a, []int{4}
}

func (m *Column) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Column.Unmarshal(m, b)
}
func (m *Column) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Column.Marshal(b, m, deterministic)
}
func (m *Column) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Column.Merge(m, src)
}
func (m *Column) XXX_Size() int {
	return xxx_messageInfo_Column.Size(m)
}
func (m *Column) XXX_DiscardUnknown() {
	xxx_messageInfo_Column.DiscardUnknown(m)
}

var xxx_messageInfo_Column proto.InternalMessageInfo

func (m *Column) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Column) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *Column) GetNullable() bool {
	if m != nil {
		return m.Nullable
	}
	return false
}

func (m *Column) GetAllowCommitTimestamp() bool {
	if m != nil {
		return m.AllowCommitTimestamp
	}
	return false
}

var E_Schema = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*Schema)(nil),
	Field:         88264,
	Name:          "spanner.ddl.schema",
	Tag:           "bytes,88264,opt,name=schema",
	Filename:      "ddl.proto",
}

var E_Column = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Column)(nil),
	Field:         88264,
	Name:          "spanner.ddl.column",
	Tag:           "bytes,88264,opt,name=column",
	Filename:      "ddl.proto",
}

func init() {
	proto.RegisterEnum("spanner.ddl.OnDelete", OnDelete_name, OnDelete_value)
	proto.RegisterType((*Schema)(nil), "spanner.ddl.Schema")
	proto.RegisterType((*Interleave)(nil), "spanner.ddl.Interleave")
	proto.RegisterType((*Index)(nil), "spanner.ddl.Index")
	proto.RegisterType((*Import)(nil), "spanner.ddl.Import")
	proto.RegisterType((*Column)(nil), "spanner.ddl.Column")
	proto.RegisterExtension(E_Schema)
	proto.RegisterExtension(E_Column)
}

func init() { proto.RegisterFile("ddl.proto", fileDescriptor_ddb477f58283b30a) }

var fileDescriptor_ddb477f58283b30a = []byte{
	// 572 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x25, 0xdb, 0x92, 0xa5, 0xb7, 0x0c, 0x4d, 0x66, 0x94, 0x68, 0x12, 0xac, 0x2a, 0x2f, 0x15,
	0xa8, 0xe9, 0x54, 0x90, 0x90, 0x26, 0x84, 0x54, 0xba, 0x4d, 0x9a, 0x80, 0x56, 0xca, 0xfa, 0xc4,
	0x4b, 0xe4, 0xc6, 0x5e, 0x6a, 0xe1, 0xd8, 0x21, 0x71, 0x60, 0xfd, 0x01, 0xbe, 0x86, 0x17, 0xfe,
	0x82, 0x7f, 0xe1, 0x27, 0x50, 0x6c, 0xa7, 0x5b, 0x61, 0xe2, 0xed, 0x9e, 0x7b, 0x6e, 0x4e, 0xee,
	0x3d, 0xbe, 0x17, 0x5a, 0x84, 0xf0, 0x30, 0x2f, 0xa4, 0x92, 0xa8, 0x5d, 0xe6, 0x58, 0x08, 0x5a,
	0x84, 0x84, 0xf0, 0xc3, 0x6e, 0x2a, 0x65, 0xca, 0xe9, 0x50, 0x53, 0x8b, 0xea, 0x6a, 0x48, 0x68,
	0x99, 0x14, 0x2c, 0x57, 0xb2, 0x30, 0xe5, 0xbd, 0xdf, 0x0e, 0x78, 0x97, 0xc9, 0x92, 0x66, 0x18,
	0x1d, 0x82, 0x4f, 0xb0, 0xc2, 0x0b, 0x5c, 0xd2, 0xc0, 0xe9, 0x3a, 0xfd, 0x56, 0xb4, 0xc6, 0xe8,
	0x00, 0x5c, 0x85, 0x17, 0x9c, 0x06, 0x5b, 0x9a, 0x30, 0x00, 0x1d, 0x41, 0x3b, 0x2f, 0x58, 0x86,
	0x8b, 0x55, 0xfc, 0x99, 0xae, 0x82, 0x6d, 0xcd, 0x81, 0x4d, 0xbd, 0xa7, 0x2b, 0xf4, 0x1a, 0x80,
	0x09, 0x45, 0x0b, 0x4e, 0xf1, 0x57, 0x1a, 0xec, 0x74, 0x9d, 0x7e, 0x7b, 0xf4, 0x38, 0xbc, 0xd5,
	0x61, 0x78, 0xb1, 0xa6, 0xa3, 0x5b, 0xa5, 0xa8, 0x0f, 0x2e, 0x13, 0x84, 0x5e, 0x07, 0x6e, 0x77,
	0xbb, 0xdf, 0x1e, 0xa1, 0xbf, 0xbe, 0x21, 0xf4, 0x3a, 0x32, 0x05, 0xe8, 0x05, 0x78, 0x2c, 0xcb,
	0x65, 0xa1, 0x02, 0x4f, 0x97, 0x3e, 0xdc, 0x2c, 0xd5, 0x54, 0x64, 0x4b, 0x7a, 0x73, 0x80, 0x9b,
	0x1f, 0x22, 0x04, 0x3b, 0x02, 0x67, 0xcd, 0xb0, 0x3a, 0x46, 0x23, 0x68, 0x49, 0x11, 0x13, 0xca,
	0xa9, 0x32, 0xc3, 0x3e, 0x18, 0x3d, 0xda, 0x50, 0x9c, 0x89, 0x53, 0x4d, 0x46, 0xbe, 0xb4, 0x51,
	0xef, 0x87, 0x03, 0xae, 0xee, 0xe9, 0x4e, 0xc5, 0x00, 0x76, 0x13, 0xc9, 0xab, 0x4c, 0x94, 0xd6,
	0xbc, 0x06, 0xa2, 0x67, 0xb0, 0x27, 0x2a, 0xce, 0xe3, 0x2b, 0xc6, 0x15, 0x2d, 0x28, 0xd1, 0x06,
	0xfa, 0xd1, 0xfd, 0x3a, 0x79, 0x6e, 0x73, 0xa8, 0x03, 0x5e, 0x25, 0xd8, 0x97, 0xca, 0xd8, 0xe7,
	0x47, 0x16, 0xd5, 0xb2, 0xa5, 0x92, 0x05, 0x13, 0x69, 0xe0, 0x1a, 0x59, 0x0b, 0xd1, 0xd3, 0x0d,
	0xd3, 0x3d, 0xf3, 0x28, 0x37, 0x99, 0xde, 0x31, 0x78, 0xc6, 0x96, 0xba, 0xdd, 0x1c, 0xab, 0x65,
	0xd3, 0x6e, 0x1d, 0xd7, 0x39, 0xb5, 0xca, 0x9b, 0x87, 0xd6, 0x71, 0xef, 0xbb, 0x03, 0xde, 0x44,
	0x37, 0x7d, 0xe7, 0x84, 0x1d, 0xf0, 0x38, 0x15, 0xa9, 0x5a, 0xea, 0x8f, 0xdc, 0xc8, 0xa2, 0x7a,
	0xa1, 0xea, 0x51, 0xf4, 0xde, 0x98, 0xd1, 0xd6, 0x18, 0xbd, 0x82, 0x0e, 0xe6, 0x5c, 0x7e, 0x8b,
	0x13, 0x99, 0x65, 0x4c, 0xc5, 0x8a, 0x65, 0xb4, 0x54, 0x38, 0xcb, 0xed, 0x98, 0x07, 0x9a, 0x9d,
	0x68, 0x72, 0xde, 0x70, 0xcf, 0x8f, 0xc1, 0x6f, 0xfc, 0x47, 0x3e, 0xec, 0x4c, 0x67, 0xd3, 0xb3,
	0xfd, 0x7b, 0xa8, 0x0d, 0xbb, 0x93, 0xf1, 0xe5, 0x64, 0x7c, 0x7a, 0xb6, 0xef, 0xa0, 0x3d, 0x68,
	0x4d, 0x67, 0xf1, 0x78, 0x32, 0xbf, 0x98, 0x4d, 0xf7, 0xb7, 0x4e, 0xa6, 0xe0, 0x95, 0x66, 0xbd,
	0x8f, 0x42, 0x73, 0x0c, 0x61, 0x73, 0x0c, 0xe1, 0x47, 0x5a, 0x96, 0x38, 0xa5, 0xb3, 0x5c, 0x31,
	0x29, 0xca, 0xe0, 0xd7, 0x4f, 0x57, 0x2f, 0xe8, 0xe6, 0x06, 0x99, 0xe3, 0x88, 0xac, 0xca, 0xc9,
	0x07, 0xf0, 0xcc, 0xf3, 0xa1, 0x27, 0xff, 0xe8, 0x9d, 0x33, 0xca, 0xc9, 0xff, 0xd5, 0x8c, 0x8b,
	0x91, 0xd5, 0x78, 0xf7, 0xf6, 0xd3, 0x9b, 0x94, 0xa9, 0x65, 0xb5, 0x08, 0x13, 0x99, 0x0d, 0xd3,
	0x22, 0x4f, 0x06, 0x49, 0x55, 0x2a, 0x99, 0x0d, 0xed, 0x47, 0xe6, 0x72, 0x93, 0x41, 0x4a, 0xc5,
	0xc0, 0xa6, 0x06, 0x84, 0xf0, 0x61, 0xce, 0xab, 0x94, 0x89, 0x85, 0xa7, 0xe9, 0x97, 0x7f, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x09, 0x09, 0x30, 0x60, 0x00, 0x04, 0x00, 0x00,
}
